### ISSUE TITLE
Can this extension be used with Bluetooth? It's blocked by Radio dependency

### ISSUE THREAD

**Issue by martinwork** [CytronTechnologies/pxt-esp8266#1]
@waiweng83 

Radio is listed as a dependency
https://github.com/CytronTechnologies/pxt-esp8266/blob/master/pxt.json#L8

This means the Bluetooth extension cannot be used at the same time.

Is the extension compatible with Bluetooth? If so, could you remove Radio from the dependency list? Maybe microphone too?

**Comment by waiweng83** [comment]
@martinwork 

Noted on this. I've removed radio and microphone from the dependencies list and updated the version to v2.0.1.

Thanks for your feedback on this.

**Comment by martinwork** [comment]
That's great news @waiweng83. This arose from a support ticket, so I'll let the customer know they can go ahead with their project. Thanks for making the change so quickly!

**Comment by waiweng83** [comment]
No problem @martinwork . It's just a quick fix that can be done with few clicks.

Thanks for pointing out the problem and the limitations.
